version: '3.2'
services:
  bownyac-session:
    container_name: bownyac-session
    image: redis
    healthcheck:
      test: exit 0
  bownyac-bd:
    container_name: bownyac-db
    build: ./db/
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "dbdata:/data/db"
    healthcheck:
      test: exit 0
  bownyac-services:
    container_name: bownyac-services
    build: ./services/
    volumes:
      - type: bind
        source: ./services
        target: /home/app
      - type: bind
        source: ./services/package.json
        target: /home/app/package.json
    depends_on:
      - bownyac-session
      - bownyac-bd
    links:
      - bownyac-bd
      - bownyac-session
    ports:
      - '4242:4242' # expose ports - HOST:CONTAINER
    environment:
      - DEBUG=services:*
volumes:
  dbdata:
    driver: local
